### ISSUE TITLE
Private Key Property not Recognized when Configured

### ISSUE THREAD

**Issue by mkandefer** [spring-cloud-stream-app-starters/sftp#42]
I've created an SFTP Source (sftp-source-kafka:2.1.0.M2) using the following definition on a local SCDF server dashboard:

```
sftp --local-dir=/tmp/inbox --filename-pattern=*.csv --task-launcher-output=true --remote-dir=/home/user/csv --private-key=file:/path/to/key/key-file.pem --username=user --host=***** --known-hosts-expression='"/path/to/hostfile/known_hosts"' | log
```

The known_hosts file and key files are both on the SCDF server and accessible. When I launch the stream I get the following error:

```
Caused by: java.lang.IllegalArgumentException: either a password or a private key is required
    at org.springframework.util.Assert.isTrue(Assert.java:118)
    at org.springframework.integration.sftp.session.DefaultSftpSessionFactory.getSession(DefaultSftpSessionFactory.java:352)
    at org.springframework.integration.sftp.session.DefaultSftpSessionFactory.getSession(DefaultSftpSessionFactory.java:57)
    at org.springframework.integration.file.remote.RemoteFileTemplate.execute(RemoteFileTemplate.java:438)

```

The stream works fine if I try it against a password based SFTP server. I've tried just the path without the "file:" in front and that causes the same error.

**Comment by garyrussell** [comment]
Reference: https://stackoverflow.com/questions/54446079/when-using-key-based-spring-cloud-stream-sftp-source-private-key-property-not-fo/54447114#54447114


The `String` property should be changed to a `Resource` (which is what the session factory expects).
